# DB connection options:
# Full list of options could be found at the following URLs:
# - https://www.psycopg.org/psycopg3/docs/api/connections.html
# - https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING
#
default_dbenv = "local_windows"
# you can specify the git command line here
#git_cmd_path = "C:/Program Files/Git/cmd/git.exe"

[dbenvs.local_windows]
host = "localhost"
port = 5432
dbname = "test1"
user = "postgres"
run_tests_by = "postgres"  
connect_timeout = 10
no_password = false
# sslmode = "prefer"

[dbenvs.local_windows_test_2]
host = "localhost"
port = 5432
dbname = "test2"
user = "postgres"
run_tests_by = "postgres"  
connect_timeout = 10
no_password = false
# sslmode = "prefer"


[dbenvs.local_macbook]
host = "localhost"
port = 5432
dbname = "esbdb7"
connect_timeout = 10
no_password = true

[dbenvs.test1]
host = "10.70.41.240"
port = 5433
dbname = "test1"
user = "dbinstall"
run_tests_by = "zapkesb"
no_password = false 
# sslmode = "prefer"

[dbenvs.dev_korotin]
host = "10.70.41.240"
port = 5433
dbname = "dev_korotin"
user = "dbinstall"
#run_tests_by = "zapkesb"  
no_password = false 
# sslmode = "prefer"

[dbenvs.ish_import_zapk_smft_01]
host = "10.70.41.240"
port = 5433
dbname = "ish_import_zapk_smft_01"
user = "dbinstall"
#run_tests_by = "zapkesb"  
no_password = false 
# sslmode = "prefer"

[dbenvs.ish_import_zapk_smft_02]
host = "10.70.41.240"
port = 5433
dbname = "ish_import_zapk_smft_02"
user = "dbinstall"
#run_tests_by = "zapkesb"  
no_password = false 
# sslmode = "prefer"

# command options
[options]
file_glob_filters = ["*.sql", "*.dump"]
file_read_encoding = "utf-8"
file_read_encoding_errors = "ignore"

# external tools to apply baseline
[tools.psql]
#executable = "/opt/homebrew/bin/psql"
# args = ["-f", "${file}", "${dbname}"]
executable = "C:/Users/andrey.larcev/NoInstaller/postgresql-18.3-2-windows-x64-binaries/pgsql/bin/psql.exe"
args = ["-h", "${host}", "-p", "${port}", "-U", "${user}", "--set=ON_ERROR_STOP=1", "-d", "${dbname}", "-f", "${file}"]
success_result_code = 0

[tools.pg_restore] 
executable = "/opt/homebrew/bin/pg_restore"
# args = ["-h", "${host}", "-U", "${user}", "--exit-on-error", "-p", "${port}", "-d", "${dbname}", "${file}"]
args = ["--exit-on-error", "-d", "${dbname}", "${file}"]
success_result_code = 0
